name: build
on: [workflow_call]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version-file: 'go.mod'
        
            - name: build go
              run: |
                go mod tidy
                GO111MODULE=on GOARCH=amd64 GOOS=linux go build -o sshbck ./cmd/main.go       
        
            - name: Build and push Docker image
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                platforms: linux/amd64
                context: .  
                file: Dockerfile  
                push: true
                tags: hanum20/sshbck:latest

